"""Sample items for `python digest.py --demo`. Not used in real runs."""
import datetime as dt

_now = dt.datetime.now(dt.timezone.utc)
def _ago(h): return _now - dt.timedelta(hours=h)

ITEMS = [
    {"title":"Talks resume on the Strait of Hormuz shipping corridor after weeks of attacks",
     "link":"https://example.com/g1","source":"New York Times · World","category":"Geopolitics",
     "when":_ago(2),"full":None,
     "summary":"Negotiators met in Muscat to restore safe passage for tankers. Insurers say premiums will stay high until attacks on merchant ships stop."},
    {"title":"Sensex ends 412 pts higher as banks lead; Nifty reclaims 24,900",
     "link":"https://example.com/1","source":"Moneycontrol · Markets","category":"Indian Capital Markets",
     "when":_ago(1),"full":None,
     "summary":"Financials drove a broad rally with HDFC Bank and ICICI adding the most points. Breadth was positive; midcaps outperformed as FIIs turned net buyers after four sessions of selling."},
    {"title":"RBI holds repo rate at 6.25%, flags sticky food inflation",
     "link":"https://example.com/2","source":"ET · Economy","category":"Indian Capital Markets",
     "when":_ago(3),"full":"The Monetary Policy Committee voted 5-1 to keep the repo rate unchanged at 6.25%, retaining its 'neutral' stance. The Governor pointed to a favourable growth outlook but cautioned that food inflation remains the key upside risk into the second half of the year, and signalled that any easing would be data-dependent through the next two prints.",
     "summary":"MPC votes 5-1 to hold; neutral stance retained amid growth optimism."},
    {"title":"Two mid-cap capital-goods names re-rate on order-book visibility",
     "link":"https://example.com/3","source":"Insights with SOIC","category":"Substacks",
     "when":_ago(5),"full":"Our thesis on the domestic capex cycle rests on three legs — ordering momentum, margin normalisation, and balance-sheet discipline. This week we walk through why the current order book gives us roughly eight quarters of revenue visibility, what the working-capital intensity tells us about execution quality, and where the market is still under-appreciating operating leverage. The punchline: consensus is modelling flat margins into a period where we think gross-margin tailwinds are structural.",
     "summary":"A deep-dive on the domestic capex cycle and why order-book visibility is mispriced."},
    {"title":"The dollar's quiet regime change and what it means for EM flows",
     "link":"https://example.com/4","source":"Pinetree Macro","category":"Substacks",
     "when":_ago(7),"full":"Positioning data suggests the market is far more short dollars than the price action implies. When we overlay real-rate differentials against portfolio flows into emerging markets, a familiar pattern emerges: the setup that preceded the 2017 and 2020 EM melt-ups is quietly reassembling. We lay out the three conditions that would confirm the regime change, and the two that would break the thesis.",
     "summary":"Real-rate differentials and EM flows are quietly rhyming with prior melt-ups."},
    {"title":"Global liquidity turns up for the first time in six months",
     "link":"https://example.com/5","source":"X · Global Macro List","category":"Global Macro & Markets",
     "when":_ago(2),"full":None,
     "summary":"Cross-border capital tracker shows the global liquidity index inflecting higher; historically a 3-6 month leading tailwind for risk assets. Thread breaks down the drivers by central bank."},
    {"title":"Why the energy-transition capex boom is a decade-long story",
     "link":"https://example.com/6","source":"X · Tech/Energy List","category":"Technology",
     "when":_ago(4),"full":None,
     "summary":"Grid interconnection queues, not manufacturing, are now the binding constraint on deployment. Utility-scale storage economics have crossed the threshold in three more states."},
    {"title":"India's services PMI hits 9-month high on export orders",
     "link":"https://example.com/7","source":"ET · Top Stories","category":"Indian Capital Markets",
     "when":_ago(6),"full":"Activity in India's dominant services sector expanded at the fastest pace in nine months, with new export business rising the most since the survey began tracking the sub-index. Input-cost inflation eased, giving firms room to protect margins even as they raised headcount at a solid clip.",
     "summary":"Services PMI at a nine-month high; export orders and hiring both accelerate."},
    {"title":"On builders, buybacks, and the arithmetic of patience",
     "link":"https://example.com/8","source":"Gautam Baid","category":"Substacks",
     "when":_ago(9),"full":"Compounding is less about the extraordinary year and more about avoiding the catastrophic one. This piece revisits three businesses where management chose buybacks over empire-building, and what the subsequent per-share value creation teaches us about capital allocation as the truest test of a management team.",
     "summary":"Capital allocation as the truest test of management — three case studies."},
    {"title":"AI-model release cadence is reshaping cloud-capex guidance",
     "link":"https://example.com/9","source":"X · Tech/Energy List","category":"Technology",
     "when":_ago(8),"full":None,
     "summary":"Hyperscaler capex commentary is diverging from street models. The read-through for power demand and networking silicon is larger than most sell-side notes assume."},
    {"title":"Gold breaks to fresh highs as central banks keep buying",
     "link":"https://example.com/10","source":"X · Global Macro List","category":"Global Macro & Markets",
     "when":_ago(10),"full":None,
     "summary":"Official-sector demand remains the marginal buyer. The de-dollarisation reserve rotation continues quietly beneath headline volatility."},
    {"title":"Smallcap IT services: the margin trough may be behind us",
     "link":"https://example.com/11","source":"X · India Markets List","category":"Indian Capital Markets",
     "when":_ago(11),"full":None,
     "summary":"Deal-win commentary and utilisation trends suggest the worst of the margin compression is passing for tier-2 names. Watch the next two quarters of book-to-bill."},
    {"title":"Pharma CDMO tailwinds and the China+1 re-rating",
     "link":"https://example.com/12","source":"Aditya Khemka","category":"Substacks",
     "when":_ago(13),"full":"The structural shift in global pharma supply chains is finally showing up in Indian CDMO order books. We separate the durable beneficiaries from the ones simply riding sentiment, and explain why the market keeps mispricing the lag between capex and revenue in this space.",
     "summary":"Separating durable CDMO beneficiaries from sentiment-driven re-rating."},
    {"title":"India's solar additions hit record as tenders shift to storage-linked projects",
     "link":"https://example.com/e1","source":"Utility Dive","category":"Energy",
     "when":_ago(3),"full":None,
     "summary":"Developers commissioned a record quarter of solar capacity, while state tenders increasingly bundle battery storage to firm up supply. Transmission delays remain the main bottleneck."},
    {"title":"Gas-to-power plants face weak dispatch as grid absorbs more renewables",
     "link":"https://example.com/e2","source":"Utility Dive","category":"Energy",
     "when":_ago(6),"full":None,
     "summary":"Plant load factors for gas-based capacity fell again as renewables covered peak demand in the afternoon. Utilities are asking regulators for capacity payments to stay viable."},
]

# Demo-only quotes so the market strip can be previewed without a network call.
QUOTES = [
    {"name": "Gold", "unit": "USD/oz", "price": 4189.99, "change": 22.40, "pct": 0.54},
    {"name": "Silver", "unit": "USD/oz", "price": 50.12, "change": -0.38, "pct": -0.75},
    {"name": "S&P 500", "price": 6712.40, "change": 38.10, "pct": 0.57},
    {"name": "Nifty 50", "price": 22520.45, "change": 288.65, "pct": 1.30},
    {"name": "USD / INR", "price": 96.72, "change": -0.16, "pct": -0.17},
    {"name": "USD / JPY", "price": 151.34, "change": 0.42, "pct": 0.28},
    {"name": "US 10Y yield", "unit": "%", "price": 4.62, "change": 0.03, "pct": 0.65},
    {"name": "India 10Y yield", "unit": "%", "price": 7.27, "change": 0.04, "pct": 0.55},
    {"name": "Brent crude", "unit": "USD/bbl", "price": 102.79, "change": -1.49, "pct": -1.43},
]
